import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useEffect,useState} from "react"
import axios from "axios"

export default function Home() {
  const [testString, setTestString] = useState('')
  const [title, setTitle] = useState('')
  useEffect(() => {
    axios.get("http://localhost:8001/api").then((response) => {
      setTestString(response.data)
    })
  })

  const Form = () => {
    const [name, setName] = useState('')
    const handleSubmit = (e) => {
        e.preventDefault()
        console.log(`Form submitted, ${name}`)
        axios.post('http://localhost:8001/post', {
          id: name
        })
    }
    return(
        <form onSubmit = {handleSubmit}>
            <input onChange = {(e) => setName(e.target.value)} value = {name}></input>
            <button type = 'submit'>Click to submit</button>
        </form>
    )
    
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Academic Committee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        {testString}
      </h1>
      <Form/>
      <h1>{title}</h1>
    </div>
  )
}
