import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useEffect,useState} from "react"
import axios from "axios"

export default function Home() {
  const [testString, setTestString] = useState("")

  useEffect(() => {
    axios.get("http://localhost:8001/api").then((response) => {
      setTestString(response.data)
    })
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        {testString}
      </h1>
    </div>
  )
}
